package com.amswh.iLIMS.project.domain;


/*
*	generated by wuzhicheng@fudan.edu.cn at 2024-05-21 14:04:23 
*/
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import jakarta.validation.constraints.*;
import lombok.Data;
import java.time.LocalDateTime;

@Data
@TableName("address")
public class Address{

	@TableId(value="addressId",type = IdType.AUTO)
	private Integer addressId;

	@NotBlank(message = "country 不能为空")
	@TableField("country")
	private String country;

	@TableField("geoId")
	private String geoId;

	@TableField("stree")
	private String stree;

	@TableField("type")
	private String type;

	@TableField("createTime")
	private LocalDateTime createTime;

}