package com.amswh.iLIMS.project.domain;


/*
*	generated by wuzhicheng@fudan.edu.cn at 2024-05-21 14:04:23 
*/
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import jakarta.validation.constraints.*;
import lombok.Data;
import java.time.LocalDateTime;

@Data
@TableName("analyte")
public class Analyte{
//
//	@TableId(value="id",type = IdType.AUTO)
//	private Integer id;
	@TableId(value="barId",type = IdType.INPUT)
	private String barId;

	@NotBlank(message = "analyteCode 不能为空")
	@TableField("analyteCode")
	private String analyteCode;

	@TableField("createTime")
	private LocalDateTime createTime;

}