package com.amswh.iLIMS.project.domain;


/*
*	generated by wuzhicheng@fudan.edu.cn at 2024-05-21 14:04:23 
*/
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import jakarta.validation.constraints.*;
import lombok.Data;
import java.time.LocalDateTime;

@Data
@TableName("dataupload")
public class DataUpload {

	@TableId(value="id",type = IdType.AUTO)
	private Integer id;

	@TableField("instrument")
	private String instrument;

	@TableField("testTime")
	private LocalDateTime testTime;

	@NotBlank(message = "inputFile 不能为空")
	@TableField("inputFile")
	private String inputFile;

	@NotBlank(message = "machineFile 不能为空")
	@TableField("machineFile")
	private String machineFile;

	@TableField("testName")
	private String testName;

	@NotBlank(message = "employeeId 不能为空")
	@TableField("employeeId")
	private String employeeId;

	@NotBlank(message = "productCode 不能为空")
	@TableField("productCode")
	private String productCode;

	@TableField("uploadTime")
	private LocalDateTime uploadTime;

}