package com.amswh.iLIMS.project.domain;


/*
*	generated by wuzhicheng@fudan.edu.cn at 2024-05-21 14:04:23 
*/
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import jakarta.validation.constraints.*;
import lombok.Data;
import java.time.LocalDateTime;

@Data
@TableName("order")
public class Order{

	@TableId(value="id",type = IdType.AUTO)
	private Integer id;

	@NotBlank(message = "orderNo 不能为空")
	@TableField("orderNo")
	private String orderNo;

	@TableField("salesPerson")
	private Integer salesPerson;

	@TableField("customer")
	private Integer customer;

	@TableField("typeId")
	private Integer typeId;

	@TableField("createTime")
	private LocalDateTime createTime;

}