package com.amswh.iLIMS.project.domain;


/*
*	generated by wuzhicheng@fudan.edu.cn at 2024-05-21 14:04:23 
*/
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import jakarta.validation.constraints.*;
import lombok.Data;

@Data
@TableName("product")
public class Product{

	@TableId(value="id",type = IdType.AUTO)
	private Integer id;

	@TableField("externalId")
	private String externalId;

	@NotBlank(message = "code 不能为空")
	@TableField("code")
	private String code;

	@NotBlank(message = "name 不能为空")
	@TableField("name")
	private String name;

	@TableField("spec")
	private String spec;

	@TableField("parentCode")
	private String parentCode;

	@TableField("projectCode")
	private String projectCode;

}