package com.amswh.iLIMS.project.domain;


/*
*	generated by wuzhicheng@fudan.edu.cn at 2024-05-21 14:04:23 
*/
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import jakarta.validation.constraints.*;
import lombok.Data;

@Data
@TableName("project")
public class Project{


	@TableId(value="code",type = IdType.NONE)
	private String code;

	@NotBlank(message = "name 不能为空")
	@TableField("name")
	private String name;

	@NotBlank(message = "type 不能为空")
	@TableField("type")
	private String type;

	@NotBlank(message = "provider 不能为空")
	@TableField("provider")
	private String provider;

}