package com.amswh.iLIMS.domain;


/*
*	generated by wuzhicheng@fudan.edu.cn at 2024-05-13 16:16:34 
*/
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import jakarta.validation.constraints.*;
import lombok.Data;
import java.time.LocalDateTime;

@Data
@TableName("analyte")
public class Analyte{

	@TableId(value="id",type = IdType.AUTO)
	@TableField("id")
	private Integer id;

	@NotBlank(message = "barCode 不能为空")
	@TableField("barCode")
	private String barCode;

	@NotBlank(message = "analyteCode 不能为空")
	@TableField("analyteCode")
	private String analyteCode;

	@NotBlank(message = "productCode 不能为空")
	@TableField("productCode")
	private String productCode;

	@TableField("createTime")
	private LocalDateTime createTime;

}