package com.amswh.iLIMS.domain;


/*
*	generated by wuzhicheng@fudan.edu.cn at 2024-05-13 16:16:34 
*/
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import jakarta.validation.constraints.*;
import lombok.Data;
import java.time.LocalDateTime;

@Data
@TableName("analyteprocess")
public class Analyteprocess{

	@TableId(value="id",type = IdType.AUTO)
	@TableField("id")
	private Integer id;

	@NotBlank(message = "analyteCode 不能为空")
	@TableField("analyteCode")
	private String analyteCode;

	@NotBlank(message = "action 不能为空")
	@TableField("action")
	private String action;

	@NotBlank(message = "status 不能为空")
	@TableField("status")
	private String status;

	@TableField("remark")
	private String remark;

	@NotBlank(message = "employeeId 不能为空")
	@TableField("employeeId")
	private String employeeId;

	@TableField("createTime")
	private LocalDateTime createTime;

}