package com.amswh.iLIMS.domain;


/*
*	generated by wuzhicheng@fudan.edu.cn at 2024-05-21 14:04:23 
*/
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import jakarta.validation.constraints.*;
import lombok.Data;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
@TableName("orderaddress")
public class OrderAddress {

	@TableId(value="id",type = IdType.AUTO)
	private Integer id;

	@NotBlank(message = "orderNo 不能为空")
	@TableField("orderNo")
	private String orderNo;

	@NotBlank(message = "name 不能为空")
	@TableField("name")
	private String name;

	@TableField("phone")
	private Integer phone;

	@TableField("geoCode")
	private String geoCode;

	@NotBlank(message = "address 不能为空")
	@TableField("address")
	private String address;

	@TableField("deadline")
	private LocalDate deadline;

	@TableField("createTime")
	private LocalDateTime createTime;

}