package com.amswh.iLIMS.domain;


/*
*	generated by wuzhicheng@fudan.edu.cn at 2024-05-13 16:16:34 
*/
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import jakarta.validation.constraints.*;
import lombok.Data;
import java.time.LocalDateTime;

@Data
@TableName("party")
public class Party{

	@TableId(value="partyId",type = IdType.AUTO)
	@TableField("partyId")
	private Integer partyId;

	@TableField("externalId")
	private String externalId;

	@NotBlank(message = "partyType 不能为空")
	@TableField("partyType")
	private String partyType;

	@TableField("phone")
	private String phone;

	@TableField("email")
	private String email;

	@TableField("createTime")
	private LocalDateTime createTime;

}