package com.amswh.iLIMS.domain;


/*
*	generated by wuzhicheng@fudan.edu.cn at 2024-05-13 16:16:34 
*/
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import jakarta.validation.constraints.*;
import lombok.Data;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
@TableName("partyrelationship")
public class Partyrelationship{

	@TableId(value="id",type = IdType.AUTO)
	@TableField("id")
	private Integer id;

	@TableField("fromId")
	private Integer fromId;

	@TableField("toId")
	private Integer toId;

	@TableField("typeId")
	private Integer typeId;

	@TableField("throughDate")
	private LocalDate throughDate;

	@TableField("createTime")
	private LocalDateTime createTime;

}