package com.amswh.iLIMS.domain;


/*
*	generated by wuzhicheng@fudan.edu.cn at 2024-05-21 14:04:23 
*/
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import jakarta.validation.constraints.*;
import lombok.Data;

@Data
@TableName("partygroup")
public class PartyGroup {

	@TableId(value="partyId",type = IdType.AUTO)
	private Integer partyId;

	@NotBlank(message = "fullName 不能为空")
	@TableField("fullName")
	private String fullName;

	@TableField("shortName")
	private String shortName;

	@TableField("country")
	private String country;

	@TableField("geoId")
	private String geoId;

}