package com.amswh.iLIMS.domain;


/*
*	generated by wuzhicheng@fudan.edu.cn at 2024-05-21 14:04:23 
*/
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import jakarta.validation.constraints.*;
import lombok.Data;

@Data
@TableName("pcrcurve")
public class PcrCurve {

	@TableId(value="id",type = IdType.AUTO)
	private Integer id;

	@NotBlank(message = "dltRN 不能为空")
	@TableField("dltRN")
	private String dltRN;

}