package com.amswh.iLIMS.domain;


/*
*	generated by wuzhicheng@fudan.edu.cn at 2024-05-13 22:08:46 
*/
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import jakarta.validation.constraints.*;
import lombok.Data;

@Data
@TableName("pcrdata")
public class Pcrdata{

	@TableId(value="id",type = IdType.AUTO)
	@TableField("id")
	private Integer id;

	@TableField("uploadId")
	private Integer uploadId;

	@NotBlank(message = "analyteCode 不能为空")
	@TableField("analyteCode")
	private String analyteCode;

	@NotBlank(message = "well 不能为空")
	@TableField("well")
	private String well;

	@NotBlank(message = "target 不能为空")
	@TableField("target")
	private String target;

	@TableField("CT")
	private Double CT;

	@NotBlank(message = "predict 不能为空")
	@TableField("predict")
	private String predict;

	@TableField("choose")
	private Integer choose;

}